Start cluster after installing ray.
Signed-off-by: mvashishtha <mahesh@ponder.io>

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -32,16 +32,7 @@ jobs:
     env:
       MODIN_ENGINE: ${{matrix.engine}}
     name: test-windows
-    steps:
-      - name: Start local ray cluster
-        run: |
-          ray start --head --port=6379 --object-store-memory=1000000000
-          while [ $? -ne 0 ]; do
-            echo "Failed to start ray cluster. retrying..."
-            ray start --head --port=6379 --object-store-memory=1000000000
-          done          
-          echo "MODIN_RAY_CLUSTER=True" >> $GITHUB_ENV
-        if: matrix.engine == 'ray'        
+    steps:      
       - uses: actions/checkout@v2
         with:
           fetch-depth: 2
@@ -68,6 +59,15 @@ jobs:
         run: |
           conda info
           conda list
+      - name: Start local ray cluster
+        run: |
+          ray start --head --port=6379 --object-store-memory=1000000000
+          while [ $? -ne 0 ]; do
+            echo "Failed to start ray cluster. retrying..."
+            ray start --head --port=6379 --object-store-memory=1000000000
+          done          
+          echo "MODIN_RAY_CLUSTER=True" >> $GITHUB_ENV
+        if: matrix.engine == 'ray'            
       - run: python -m pytest ${{matrix.test-task}}
         if: matrix.test-task != 'modin/pandas/test/test_io.py'
       - timeout-minutes: 30
